import { Auction } from '@/types';

const now = new Date();
const hours = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000);

export const mockAuctions: Auction[] = [
  {
    id: '1',
    sellerId: 'seller1',
    sellerName: 'AutoHaus Premium',
    sellerCompany: 'AutoHaus Premium GmbH',
    car: {
      id: 'car1',
      title: '2019 Porsche 911 Carrera S',
      make: 'Porsche',
      model: '911 Carrera S',
      year: 2019,
      mileage: 23500,
      fuelType: 'Benzin',
      transmission: 'PDK',
      power: '450 PS',
      color: 'GT-Silber Metallic',
      description: 'Wunderschöner Porsche 911 Carrera S in GT-Silber Metallic. PDK-Getriebe, Sport Chrono Paket, BOSE Surround Sound, LED Matrix Scheinwerfer. Scheckheftgepflegt mit voller Porsche-Historie.',
      images: ['https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800'],
      location: 'München',
      features: ['PDK', 'Sport Chrono', 'BOSE Sound', 'LED Matrix'],
    },
    startPrice: 75000,
    currentBid: 89500,
    minimumIncrement: 500,
    bidCount: 23,
    highestBidderId: 'user3',
    highestBidderName: 'MaxM.',
    startTime: hours(-2),
    endTime: hours(4),
    status: 'active',
    buyerFee: 250,
    approved: true,
    winnerPaid: false,
    createdAt: hours(-48),
  },
  {
    id: '2',
    sellerId: 'seller2',
    sellerName: 'SportWagen Stuttgart',
    sellerCompany: 'SportWagen Stuttgart GmbH',
    car: {
      id: 'car2',
      title: '2021 BMW M4 Competition',
      make: 'BMW',
      model: 'M4 Competition',
      year: 2021,
      mileage: 15200,
      fuelType: 'Benzin',
      transmission: 'Automatik',
      power: '510 PS',
      color: 'Sao Paulo Gelb',
      description: 'BMW M4 Competition in Sao Paulo Gelb. M xDrive, Carbon Dach, Harman Kardon, Head-Up Display. Unfallfrei, erster Besitzer.',
      images: ['https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800'],
      location: 'Stuttgart',
      features: ['M xDrive', 'Carbon Dach', 'Harman Kardon', 'Head-Up Display'],
    },
    startPrice: 65000,
    currentBid: 72000,
    minimumIncrement: 500,
    bidCount: 15,
    highestBidderId: 'user5',
    highestBidderName: 'ThomasK.',
    startTime: hours(-1),
    endTime: hours(6),
    status: 'active',
    buyerFee: 250,
    approved: true,
    winnerPaid: false,
    createdAt: hours(-24),
  },
  {
    id: '3',
    sellerId: 'seller3',
    sellerName: 'Prestige Cars HH',
    sellerCompany: 'Prestige Cars Hamburg GmbH',
    car: {
      id: 'car3',
      title: '2020 Mercedes-AMG GT 63 S',
      make: 'Mercedes-Benz',
      model: 'AMG GT 63 S',
      year: 2020,
      mileage: 31000,
      fuelType: 'Benzin',
      transmission: 'Automatik',
      power: '639 PS',
      color: 'Selenitgrau',
      description: 'Mercedes-AMG GT 63 S 4MATIC+ in Selenitgrau. V8 Biturbo mit 639 PS, AMG Performance Sitze, Burmester 3D Sound, AMG Aerodynamik-Paket.',
      images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800'],
      location: 'Hamburg',
      features: ['AMG Performance', 'Burmester 3D', 'Aerodynamik-Paket'],
    },
    startPrice: 95000,
    currentBid: 112000,
    minimumIncrement: 500,
    bidCount: 31,
    highestBidderId: 'user7',
    highestBidderName: 'StefanW.',
    startTime: hours(-5),
    endTime: hours(1),
    status: 'active',
    buyerFee: 250,
    approved: true,
    winnerPaid: false,
    createdAt: hours(-72),
  },
  {
    id: '4',
    sellerId: 'seller4',
    sellerName: 'Elite Autos Berlin',
    sellerCompany: 'Elite Autos Berlin GmbH',
    car: {
      id: 'car4',
      title: '2022 Audi RS6 Avant',
      make: 'Audi',
      model: 'RS6 Avant',
      year: 2022,
      mileage: 8700,
      fuelType: 'Benzin',
      transmission: 'Automatik',
      power: '600 PS',
      color: 'Nardograu',
      description: 'Audi RS6 Avant in Nardograu. 600 PS V8 Biturbo, RS Sportabgasanlage, Carbon Optik Paket, Panorama-Glasdach, Matrix LED.',
      images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800'],
      location: 'Berlin',
      features: ['RS Sportabgas', 'Carbon Optik', 'Panoramadach', 'Matrix LED'],
    },
    startPrice: 110000,
    currentBid: 118500,
    minimumIncrement: 500,
    bidCount: 12,
    highestBidderId: 'user2',
    highestBidderName: 'AnnaL.',
    startTime: hours(-0.5),
    endTime: hours(12),
    status: 'active',
    buyerFee: 250,
    approved: true,
    winnerPaid: false,
    createdAt: hours(-12),
  },
  {
    id: '5',
    sellerId: 'seller5',
    sellerName: 'Klassik Garage',
    sellerCompany: 'Klassik Garage Düsseldorf',
    car: {
      id: 'car5',
      title: '1989 Porsche 964 Carrera 4',
      make: 'Porsche',
      model: '964 Carrera 4',
      year: 1989,
      mileage: 124000,
      fuelType: 'Benzin',
      transmission: 'Manuell',
      power: '250 PS',
      color: 'Grand Prix Weiß',
      description: 'Klassiker! Porsche 964 Carrera 4 in Grand Prix Weiß. G50 Getriebe, komplett restauriert 2021, TÜV neu, H-Kennzeichen möglich.',
      images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800'],
      location: 'Düsseldorf',
      features: ['G50 Getriebe', 'H-Kennzeichen', 'TÜV neu', 'Restauriert 2021'],
    },
    startPrice: 85000,
    currentBid: 0,
    minimumIncrement: 500,
    bidCount: 0,
    highestBidderId: '',
    highestBidderName: '',
    startTime: hours(2),
    endTime: hours(26),
    status: 'upcoming',
    buyerFee: 250,
    approved: true,
    winnerPaid: false,
    createdAt: hours(-6),
  },
  {
    id: '6',
    sellerId: 'seller6',
    sellerName: 'E-Mobility Frankfurt',
    sellerCompany: 'E-Mobility Frankfurt GmbH',
    car: {
      id: 'car6',
      title: '2023 Tesla Model S Plaid',
      make: 'Tesla',
      model: 'Model S Plaid',
      year: 2023,
      mileage: 5200,
      fuelType: 'Elektro',
      transmission: 'Automatik',
      power: '1020 PS',
      color: 'Midnight Cherry Red',
      description: 'Tesla Model S Plaid in Midnight Cherry Red. 1020 PS, 0-100 in 2,1s, Full Self-Driving, Yoke Lenkrad, 21" Arachnid Felgen.',
      images: ['https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800'],
      location: 'Frankfurt',
      features: ['Full Self-Driving', 'Yoke Lenkrad', '21" Arachnid', 'Autopilot'],
    },
    startPrice: 80000,
    currentBid: 86000,
    minimumIncrement: 500,
    bidCount: 8,
    highestBidderId: 'user9',
    highestBidderName: 'ChrisP.',
    startTime: hours(-3),
    endTime: hours(8),
    status: 'active',
    buyerFee: 250,
    approved: true,
    winnerPaid: false,
    createdAt: hours(-36),
  },
];
