services:
  - type: web
    name: autobid
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: "AIzaSyC2P0o_VUtfFy2qQDMuyZmvwXMOT0KNZ-I"
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: "autobid-5e23d.firebaseapp.com"
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: "autobid-5e23d"
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: "autobid-5e23d.firebasestorage.app"
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "901745420058"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: "1:901745420058:web:c396c3849776cee54e6ea3"
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NEXT_PUBLIC_BUYER_FEE
        value: "250"
